name = "GradientRobustMultiPhysics"
uuid = "0802c0ca-1768-4022-988c-6dd5f9588a11"
authors = ["Christian Merdon <christian.merdon@wias-berlin.de>"]
version = "0.9.7"

[deps]
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
ExtendableSparse = "95c220a8-a1cf-11e9-0c77-dbfce5f500b3"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GridVisualize = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
SparsityDetection = "684fba80-ace3-11e9-3d08-3bc7ed6f96df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DiffResults = "^1.0.0"
DocStringExtensions = "^0.8"
ExtendableGrids = "0.9.4"
ExtendableSparse = "0.6.6"
ForwardDiff = "^0.10"
GridVisualize = "^0.5"
SparseDiffTools = "^1.19"
SparsityDetection = "0.3.4"
StaticArrays = "1"
julia = "^1.6"
